spring:
  kafka:
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      group-id: stock-group
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    properties:
      schema.registry.url: http://localhost:8081

testapp:
  kafka:
    topic:
      stock:
        name: stonks-topic
        partitions: 1
        replication: 1
