spring:

  kafka:
    streams:
      application-id: ${spring.application.name}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: stock-group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.vrm.test.*
    bootstrap-servers: localhost:9092

testapp:
  kafka:
    topic:
      stock:
        name: json-stonks-topic
        partitions: 1
        replication: 1
